## Settings
title: KalanBlog
owner: "Kalan"
url: "https://kalanliao.github.io"
baseurl: "/a2FsYW5saWFv"
permalink: /:title/
description: ""
markdown: kramdownf
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "kalan.liao@live.com"
github: "kalanliao"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Designed by Kalan, All Rights Reserved"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"